library(shiny)
shinyUI(pageWithSidebar(
  headerPanel("Predicting Sepal Width Given Petal Width by Iris Species"),
  sidebarPanel(
    radioButtons("species", "select iris species", c("I. setosa" = "I.setosa", "I. versicolor" = "I.versicolor", "I. virginica" = "I.virginica")),
    numericInput("petalWidth", "select petal width (cm)", 0.0, min = 0.0, max = 2.5, step = 0.1),
    p("The linear regression model generated by R's lm() function for each iris species (with intercept and slope shown) is:"),
    p("I. setosa"),
    verbatimTextOutput("setosaModelCoeff"),
    p("I. versicolor"),
    verbatimTextOutput("versicolorModelCoeff"),
    p("I. virginica"),
    verbatimTextOutput("virginicaModelCoeff")
  ),
  mainPanel(
    h4("Documentation"),
    p("In Fisher's famous Iris data set, we can see the relationship between sepal and petal length by species (as shown in the plot below.)  You can make use of a simple regression model to predict sepal width by setting the species and petal width in the panel on the left.  The app will automatically react and update your input and predicted output in the pane below."),
    plotOutput("sepalPetalPlot"),
    p("Using the linear model generated by R's lm() function for each species (as displayed in the left panel), for the selected iris species and petal width:"),
    textOutput("selectedSpecies"),
    textOutput("selectedPetalWidth"),
    h5("the predicted sepal width is:"),
    verbatimTextOutput("predictedSepalWidth")
  )
  ))